version: '3'

services:

  node:
    build:
      context: node
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh sh -c "npm install && node index.js"
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
      # - /usr/src/app/node_modules
    tty: true
    # ports:
    #   - "3000:3000"
    depends_on:
      - db
      
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    build: 
      context: nginx
    # image: nginx:1.15.0-alpine
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - node-network
    ports:
      - "8080:80"    
    depends_on:
      - node

networks:
  node-network:
    driver: bridge